---
Name: ecommerce_product_variation
Before: 'mysite/*'
After: 'framework/*','cms/*','ecommerce/*'
---
Product:
  extensions:
    - ProductWithVariationDecorator

Product_Controller:
  extensions:
    - ProductWithVariationDecorator_Controller
  allowed_actions:
    - VariationForm
    - addvariation


LeftAndMain:
  extra_requirements_javascript:
    - framework/thirdparty/jquery/jquery.js
    - framework/thirdparty/jquery-entwine/dist/jquery.entwine-dist.js
    - ecommerce_product_variation/javascript/CreateEcommerceVariationsField.js
  extra_requirements_themedCss:
    - CreateEcommerceVariationsField


EcommerceDatabaseAdmin:
  extensions:
    - EcommerceProductVariationTaskDeleteVariations_EXT



---
Only:
  classexists: 'DataObjectSorterDOD'
---

ProductAttributeValue:
  extensions:
    - DataObjectSorterDOD

ProductAttributeType:
  extensions:
    - DataObjectSorterDOD
