---
Name: ecommerce_product_variation
Before: 'mysite/*'
After: 'framework/*','cms/*','ecommerce/*'
---
Product:
  extensions:
    - ProductWithVariationDecorator

Product_Controller:
  extensions:
    - ProductWithVariationDecorator_Controller
  allowed_actions:
    - VariationForm
    - addvariation

EcommerceDatabaseAdmin:
  extensions:
    - EcommerceProductVariationTaskDeleteVariations_EXT

ProductsAndGroupsModelAdmin:
  managed_modules:
    - ProductVariation
    - ProductAttributeValue
    - ProductAttributeType

---
Only:
  classexists: 'DataObjectSorterDOD'
---

ProductAttributeValue:
  extensions:
    - DataObjectSorterDOD

ProductAttributeType:
  extensions:
    - DataObjectSorterDOD
