---
Name: ecommerce_product_variation_routes
After: framework/routes#coreroutes
---
Director:
  rules:
    'createecommercevariations//$Action/$ProductID' : 'CreateEcommerceVariations'
    'createecommercevariationsbatch//$Action' : 'CreateEcommerceVariations_Batch'
